# Generated by Django 4.2.6 on 2023-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='discription',
            field=models.TextField(max_length=500),
        ),
    ]
