# Generated by Django 4.2.6 on 2023-12-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_watermarked_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='watermarked_image',
        ),
    ]
